# Generated by Django 5.1.6 on 2025-03-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='thumbnail',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
